Repository mbti-nf-team/soople, pull requests merged in 2022-01, with the labels that each got.

#134 [Fix] Next-Auth를 걷어내고 Firebase Authentication를 적용하라
  .gitignore
  __mocks__/firebase/analytics.js
  __mocks__/firebase/app.js
  __mocks__/firebase/auth.js
  __mocks__/firebase/firestore.js
  __mocks__/next-auth/client.js
  fixtures/session.ts
  package.json
  src/__mocks__/firebase/app.js
  src/components/auth/SocialButtonGroup.test.tsx
  src/components/auth/SocialButtonGroup.tsx
  src/components/common/AuthProvider.test.tsx
  src/components/common/AuthProvider.tsx
  src/components/common/DropDown.test.tsx
  src/components/common/DropDown.tsx
  src/components/common/Header.test.tsx
  src/components/common/Header.tsx
  src/components/common/UserNavbar.test.tsx
  src/components/common/UserNavbar.tsx
  src/containers/auth/SignInModalContainer.test.tsx
  src/containers/auth/SignInModalContainer.tsx
  src/containers/auth/SignUpContainer.test.tsx
  src/containers/auth/SignUpContainer.tsx
  src/containers/common/HeaderContainer.test.tsx
  src/containers/common/HeaderContainer.tsx
  src/containers/detail/CommentsContainer.test.tsx
  src/containers/detail/CommentsContainer.tsx
  src/containers/write/PublishModalContainer.test.tsx
  src/containers/write/PublishModalContainer.tsx
  src/containers/write/WriteFormContainer.test.tsx
  src/containers/write/WriteFormContainer.tsx
  src/pages/_app.page.tsx
  src/pages/api/auth/[...nextauth].api.ts
  src/pages/detail/[id].test.tsx
  src/pages/index.page.tsx
  src/pages/index.test.tsx
  src/pages/signup.page.tsx
  src/pages/signup.test.tsx
  src/pages/write.test.tsx
  src/reducers/authSlice.test.ts
  src/reducers/authSlice.ts
  src/reducers/rootReducer.test.ts
  src/reducers/rootReducer.ts
  src/services/api/__mocks__/auth.ts
  src/services/api/auth.test.ts
  src/services/api/auth.ts
  src/services/api/comment.test.ts
  src/services/api/comment.ts
  src/services/api/group.test.ts
  src/services/api/group.ts
  src/services/api/tagsCount.test.ts
  src/services/api/tagsCount.ts
  src/services/firebase/__mock__/index.js
  src/services/firebase/firebaseAdmin.ts
  src/services/firebase/index.test.ts
  src/services/firebase/index.ts
  types/next-auth.d.ts
  yarn.lock
Labels: Bugfix/Function, Refactor

#135 [Fix] Firebase v.9.6가 vercel prod에서 깨지는 오류를 수정하라
  package.json
  yarn.lock
Labels: Bugfix/Function

#137 [Feature] 모집글 상세 페이지의 상단부분이 작성자와 아닐 때에 따라 다르게 보이게 하라
  package.json
  src/components/common/Button.test.tsx
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/detail/ApplyStatusButtonGroup.test.tsx
  src/components/detail/ApplyStatusButtonGroup.tsx
  src/components/detail/DetailHeaderSection.test.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/services/api/auth.ts
  yarn.lock
Labels: Feature/Function, UI/UX

#139 [Feature] 디자인 시스템의 font style을 공통으로 정의하라
  src/components/auth/SignInError.tsx
  src/components/auth/SignInModal.tsx
  src/components/auth/SocialButtonGroup.tsx
  src/components/common/Button.test.tsx
  src/components/common/Button.tsx
  src/components/common/DropDown.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/components/write/TagForm.tsx
  src/styles/GlobalStyles.tsx
  src/styles/fontStyles.test.ts
  src/styles/fontStyles.ts
Labels: UI/UX

#141 [Feature] 댓글 작성자는 댓글을 삭제하도록 하라
  __mocks__/firebase/firestore.js
  src/components/detail/CommentView.test.tsx
  src/components/detail/CommentView.tsx
  src/components/detail/CommentsView.test.tsx
  src/components/detail/CommentsView.tsx
  src/components/detail/DetailContentsSection.tsx
  src/containers/detail/CommentsContainer.test.tsx
  src/containers/detail/CommentsContainer.tsx
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/services/api/__mocks__/comment.ts
  src/services/api/comment.test.ts
  src/services/api/comment.ts
  src/styles/GlobalStyles.tsx
Labels: Feature/Function

#143 [Feature] Confirm Modal 공통 컴포넌트를 구현하라
  src/components/common/Button.tsx
  src/components/common/ConfirmModal.test.tsx
  src/components/common/ConfirmModal.tsx
  src/components/detail/modal/AskDeleteComment.test.tsx
  src/components/detail/modal/AskDeleteComment.tsx
  src/pages/text.page.tsx
  src/styles/zIndexes.ts
Labels: Feature/Function, UI/UX

#145 [UI & UX] 컴포넌트 CSS 추가 적용하라
  src/components/common/Button.test.tsx
  src/components/common/Button.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/Header.test.tsx
  src/components/common/Header.tsx
  src/components/detail/CommentView.test.tsx
  src/components/detail/CommentView.tsx
  src/components/detail/CommentsView.test.tsx
  src/components/detail/modal/AskDeleteCommentModal.test.tsx
  src/components/detail/modal/AskDeleteCommentModal.tsx
  src/containers/common/HeaderContainer.test.tsx
  src/containers/common/HeaderContainer.tsx
  src/containers/detail/CommentsContainer.test.tsx
  src/pages/_app.page.tsx
  src/pages/detail/[id].test.tsx
  src/pages/index.test.tsx
  src/pages/text.page.tsx
  src/styles/GlobalStyles.tsx
Labels: UI/UX

#148 [Feature] 모집 완료 상태 및 조회수 상태를 추가하라
  fixtures/group.ts
  src/components/detail/ApplicantStatusButton.test.tsx
  src/components/detail/ApplicantStatusButton.tsx
  src/components/detail/CommentForm.tsx
  src/components/detail/CommentView.tsx
  src/components/detail/DetailHeaderSection.test.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/components/detail/WriterStatusButtons.test.tsx
  src/components/detail/WriterStatusButtons.tsx
  src/components/home/RecruitPost.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/hooks/useCurrentTime.test.ts
  src/hooks/useCurrentTime.ts
  src/models/group.ts
  src/services/api/group.test.ts
  src/services/api/group.ts
  src/styles/Divider.ts
Labels: Feature/Function

#149 [Feature] Textarea 공통 컴포넌트를 구현하라
  src/components/common/Textarea.test.tsx
  src/components/common/Textarea.tsx
  src/components/detail/CommentForm.test.tsx
  src/components/detail/CommentForm.tsx
  src/containers/detail/CommentsContainer.test.tsx
  src/containers/detail/CommentsContainer.tsx
  src/styles/GlobalStyles.tsx
Labels: Feature/Function, UI/UX

#151 [Feature] 사용자는 스터디 및 프로젝트를 신청할 수 있게하라
  .eslintrc.js
  fixtures/applicants.ts
  fixtures/initialStore.ts
  src/components/common/Button.tsx
  src/components/common/FormModal.test.tsx
  src/components/common/FormModal.tsx
  src/components/common/Textarea.tsx
  src/components/detail/ApplicantStatusButton.test.tsx
  src/components/detail/ApplicantStatusButton.tsx
  src/components/detail/ApplyFormModal.test.tsx
  src/components/detail/ApplyFormModal.tsx
  src/components/detail/ApplyStatusButtonGroup.test.tsx
  src/components/detail/ApplyStatusButtonGroup.tsx
  src/components/detail/DetailHeaderSection.test.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/models/group.ts
  src/pages/detail/[id].test.tsx
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/services/api/__mocks__/applicants.ts
  src/services/api/applicants.test.ts
  src/services/api/applicants.ts
  src/styles/zIndexes.ts
Labels: Feature/Function

#155 [Feature] 스터디 또는 프로젝트를 신청한 사용자는 신청을 취소할 수 있게하라
  src/components/detail/ApplicantStatusButton.test.tsx
  src/components/detail/ApplicantStatusButton.tsx
  src/components/detail/DetailHeaderSection.test.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/components/detail/DetailStatusButton.test.tsx
  src/components/detail/DetailStatusButton.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/services/api/__mocks__/applicants.ts
  src/services/api/applicants.test.ts
  src/services/api/applicants.ts
Labels: Feature/Function

#157 [Feature] 신청 취소시 신청 취소 모달창 로직을 추가하라
  src/components/common/Header.tsx
  src/components/detail/ApplicantStatusButton.test.tsx
  src/components/detail/ApplicantStatusButton.tsx
  src/components/detail/CommentView.tsx
  src/components/detail/CommentsView.tsx
  src/components/detail/DetailContentsSection.tsx
  src/components/detail/modal/AskApplyCancelModal.test.tsx
  src/components/detail/modal/AskApplyCancelModal.tsx
  src/components/home/RecruitPost.tsx
  src/components/home/RecruitPosts.tsx
  src/components/home/TagsBar.tsx
  src/containers/common/HeaderContainer.test.tsx
  src/containers/common/HeaderContainer.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/styles/GlobalStyles.tsx
Labels: Feature/Function

#159 [Feature] 신청 모달 스타일을 적용하라
  .eslintrc.js
  src/components/common/FormModal.test.tsx
  src/components/common/FormModal.tsx
  src/components/common/Textarea.tsx
  src/components/detail/ApplyFormModal.tsx
  src/styles/palette.ts
Labels: Feature/Function, UI/UX

#161 [Improve] 조건에 따라 디테일 페이지의 버튼 및 날짜 상태가 다르게 나타나게하라
  src/components/detail/ApplicantStatusButton.test.tsx
  src/components/detail/ApplicantStatusButton.tsx
  src/components/detail/DetailHeaderSection.test.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/components/detail/DetailStatusButton.tsx
  src/components/home/RecruitPost.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/hooks/useCurrentTime.test.ts
  src/hooks/useCurrentTime.ts
  src/hooks/useRecruitDateStatus.test.ts
  src/hooks/useRecruitDateStatus.ts
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: Improve/Function

#163 [uiux] 텍스트 스타일의 단위를 px에서 rem으로 변경하라
  src/components/common/Button.test.tsx
  src/components/home/RecruitPost.tsx
  src/styles/fontStyles.test.ts
  src/styles/fontStyles.ts
Labels: UI/UX

#166 [Fix] 자잘한 버그사항들을 수정하라
  src/assets/icons/img_logo_conners.svg
  src/components/auth/SignInModal.tsx
  src/components/auth/SocialButtonGroup.tsx
  src/components/common/FormModal.test.tsx
  src/components/common/FormModal.tsx
  src/components/common/Header.tsx
  src/components/detail/ApplicantStatusButton.tsx
  src/components/detail/ApplyFormModal.tsx
  src/components/detail/CommentForm.tsx
  src/components/detail/DetailContentsSection.tsx
  src/components/detail/DetailHeaderSection.test.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/containers/detail/DetailHeaderContainer.tsx
Labels: Bugfix/UI, Bugfix/Function

#168 [Improve] Button 컴포넌트의 hover 속성을 css를 opacity로 변경하라
  public/favicon.ico
  public/vercel.svg
  src/components/common/Button.test.tsx
  src/components/common/Button.tsx
  src/components/detail/ApplyFormModal.tsx
  src/styles/GlobalStyles.tsx
Labels: Improve/Function, UI/UX

#170 [Add] Conners favicon 추가하라
  README.md
  images/conners.png
  images/mock-profile.png
  images/profile.jpeg
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/site.webmanifest
  src/pages/_document.page.tsx
Labels: Update/Documentation, 🛠 Setting

#172 [Feature] 신청현황 페이지는 작성자만 접근이 가능하도록 하라
  __mocks__/firebase-admin.js
  package.json
  src/components/common/Core.tsx
  src/containers/auth/SignInModalContainer.tsx
  src/containers/home/RecruitPostsContainer.test.tsx
  src/containers/home/RecruitPostsContainer.tsx
  src/pages/_app.page.tsx
  src/pages/api/authenticated.api.ts
  src/pages/api/authenticated.test.ts
  src/pages/detail/[id]/applicants.page.tsx
  src/pages/detail/[id]/applicants.test.tsx
  src/pages/index.test.tsx
  src/services/firebase/firebaseAdmin.test.ts
  src/services/firebase/firebaseAdmin.ts
  src/styles/GlobalStyles.tsx
  yarn.lock
Labels: Feature/Function

#174 [Feature] 글 작성자는 신청 현황 페이지의 신청자 리스트를 볼 수 있게하라
  fixtures/applicant.ts
  src/components/applicants/ApplicantItem.test.tsx
  src/components/applicants/ApplicantItem.tsx
  src/components/applicants/ApplicationStatus.test.tsx
  src/components/applicants/ApplicationStatus.tsx
  src/components/applicants/Header.test.tsx
  src/components/applicants/Header.tsx
  src/components/common/Core.tsx
  src/components/detail/ApplicantStatusButton.test.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/components/detail/DetailStatusButton.tsx
  src/components/detail/WriterStatusButtons.test.tsx
  src/components/detail/WriterStatusButtons.tsx
  src/containers/applicants/ApplicationStatusContainer.test.tsx
  src/containers/applicants/ApplicationStatusContainer.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/pages/detail/[id].page.tsx
  src/pages/detail/[id].test.tsx
  src/pages/detail/[id]/applicants.page.tsx
  src/pages/detail/[id]/applicants.test.tsx
  src/reducers/groupSlice.test.ts
  src/services/api/applicants.test.ts
  src/styles/GlobalStyles.tsx
  src/styles/Layout.tsx
Labels: Feature/Function

#176 [Feature] Sub 공통 헤더 컴포넌트를 구현하라
  src/components/applicants/Header.test.tsx
  src/components/common/SubHeader.test.tsx
  src/components/common/SubHeader.tsx
  src/components/write/WriteHeader.test.tsx
  src/components/write/WriteHeader.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.tsx
  src/containers/write/WriteHeaderContainer.test.tsx
  src/containers/write/WriteHeaderContainer.tsx
  src/pages/detail/[id]/applicants.page.tsx
  src/pages/write.page.tsx
Labels: Feature/Function

#178 [Feature] 작성자는 신청자의 참여 여부를 선택 및 해제할 수 있게하라
  src/components/applicants/ApplicantItem.test.tsx
  src/components/applicants/ApplicantItem.tsx
  src/components/applicants/ApplicationStatus.test.tsx
  src/components/applicants/ApplicationStatus.tsx
  src/containers/applicants/ApplicationStatusContainer.test.tsx
  src/containers/applicants/ApplicationStatusContainer.tsx
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/services/api/__mocks__/applicants.ts
  src/services/api/applicants.test.ts
  src/services/api/applicants.ts
Labels: Feature/Function

#180 [Feature] 모집 완료 플로우를 구현하라
  src/components/applicants/ApplicationStatusHeader.test.tsx
  src/components/applicants/ApplicationStatusHeader.tsx
  src/components/applicants/CompleteApplyFormModal.test.tsx
  src/components/applicants/CompleteApplyFormModal.tsx
  src/components/common/FormModal.test.tsx
  src/components/common/FormModal.tsx
  src/components/common/SubHeader.tsx
  src/containers/applicants/ApplicationStatusContainer.test.tsx
  src/containers/applicants/ApplicationStatusContainer.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.tsx
  src/pages/detail/[id]/applicants.page.tsx
  src/pages/detail/[id]/applicants.test.tsx
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/services/api/__mocks__/group.ts
  src/services/api/group.test.ts
  src/services/api/group.ts
Labels: Feature/Function

#182 [Feature] 카드 컴포넌트에 CSS를 적용한다.
  src/components/home/RecruitPost.tsx
  src/components/home/RecruitPosts.tsx
  src/styles/Divider.ts
Labels: Feature/Function, UI/UX

#184 [Fix] 모집 완료 후 비로그인 및 승인되지 않은 유저한테도 팀원보기 버튼이 보이는 오류를 수정하라
  src/components/applicants/ApplicantItem.tsx
  src/components/applicants/CompleteApplyFormModal.tsx
  src/components/common/FormModal.test.tsx
  src/components/common/FormModal.tsx
  src/components/detail/ApplicantStatusButton.test.tsx
  src/components/detail/ApplicantStatusButton.tsx
Labels: Bugfix/Function

#186 [Feature] 모집 마감시간 이전인 경우 모집 완료 모달창에서 주의 메시지가 나타나게하라
  src/components/applicants/ApplicantItem.tsx
  src/components/applicants/ApplicationStatusHeader.test.tsx
  src/components/applicants/ApplicationStatusHeader.tsx
  src/components/applicants/CompleteApplyFormModal.test.tsx
  src/components/applicants/CompleteApplyFormModal.tsx
  src/components/common/FormModal.tsx
  src/components/detail/ApplyFormModal.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.tsx
  src/hooks/useCurrentTime.ts
  src/hooks/useRecruitDateStatus.ts
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: Feature/Function

#188 [Feature] Input 공통 컴포넌트 구현하라
  .eslintrc.js
  src/components/common/Input.test.tsx
  src/components/common/Input.tsx
  src/components/detail/ApplyFormModal.test.tsx
  src/components/detail/ApplyFormModal.tsx
  src/styles/GlobalStyles.tsx
Labels: Feature/Function

#190 [Fix] 포트폴리오 clear 버튼 클릭 후 submit 되지 않는 오류를 수정하라
  src/components/detail/ApplyFormModal.tsx
  src/components/detail/DetailHeaderSection.test.tsx
  src/components/detail/DetailHeaderSection.tsx
  src/reducers/rootReducer.test.ts
  src/reducers/rootReducer.ts
Labels: Bugfix/Function

#198 [Feature] 모집 마감 안보기 switch 버튼을 구현하라
  package.json
  src/components/common/SwitchButton.test.tsx
  src/components/common/SwitchButton.tsx
  src/containers/home/StatusBarContainer.test.tsx
  src/containers/home/StatusBarContainer.tsx
  yarn.lock
Labels: Feature/Function, UI/UX

#196 [UI/UX] myinfo 페이지의 탭 스타일과 Empty State를 구현
  src/components/myInfo/MyInfoTab.test.tsx
  src/components/myInfo/MyInfoTab.tsx
  src/pages/myinfo/applied.page.tsx
  src/pages/myinfo/recruited.page.tsx
Labels: UI/UX

#200 [Feature] 모집 마감 안보기 상태에 따라 리스트들이 filtering되게 하라
  src/containers/home/RecruitPostsContainer.tsx
  src/containers/home/StatusBarContainer.test.tsx
  src/containers/home/StatusBarContainer.tsx
  src/models/group.ts
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/services/api/group.test.ts
  src/services/api/group.ts
  src/services/firebase/getQuery.test.ts
  src/services/firebase/getQuery.ts
  src/utils/utils.ts
Labels: Feature/Function

#203 [Feature] 내 정보 페이지에서 내가 모집한 팀을 볼 수 있게하라
  fixtures/initialStore.ts
  src/components/myInfo/RecruitedPost.test.tsx
  src/components/myInfo/RecruitedPost.tsx
  src/components/myInfo/RecruitedPosts.test.tsx
  src/components/myInfo/RecruitedPosts.tsx
  src/containers/home/StatusBarContainer.tsx
  src/containers/myInfo/RecruitedPostsContainer.test.tsx
  src/containers/myInfo/RecruitedPostsContainer.tsx
  src/pages/myinfo/recruited.page.tsx
  src/pages/myinfo/recruited.test.tsx
  src/reducers/myInfoSlice.test.ts
  src/reducers/myInfoSlice.ts
  src/reducers/rootReducer.test.ts
  src/reducers/rootReducer.ts
  src/services/api/__mocks__/group.ts
  src/services/api/group.test.ts
  src/services/api/group.ts
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: Feature/Function

#204 [Feature] 내 정보 페이지에서 내가 신청한 팀을 볼 수 있게 하라
  fixtures/group.ts
  fixtures/initialStore.ts
  src/components/applicants/ApplicationStatusHeader.tsx
  src/components/myInfo/MyGroup.test.tsx
  src/components/myInfo/MyGroup.tsx
  src/components/myInfo/MyGroups.test.tsx
  src/components/myInfo/MyGroups.tsx
  src/components/myInfo/RecruitedPosts.test.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.tsx
  src/containers/myInfo/AppliedGroupsContainer.test.tsx
  src/containers/myInfo/AppliedGroupsContainer.tsx
  src/containers/myInfo/RecruitedGroupsContainer.test.tsx
  src/containers/myInfo/RecruitedGroupsContainer.tsx
  src/models/group.ts
  src/pages/myinfo/applied.page.tsx
  src/pages/myinfo/applied.test.tsx
  src/pages/myinfo/recruited.page.tsx
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/reducers/myInfoSlice.test.ts
  src/reducers/myInfoSlice.ts
  src/reducers/rootReducer.test.ts
  src/services/api/__mocks__/applicants.ts
  src/services/api/__mocks__/group.ts
  src/services/api/applicants.test.ts
  src/services/api/applicants.ts
  src/services/api/group.test.ts
  src/services/api/group.ts
  src/utils/firestore.test.ts
  src/utils/firestore.ts
Labels: Feature/Function

#206 [Fix] 로그아웃시 메인 페이지로 이동시켜라
  src/containers/common/HeaderContainer.test.tsx
  src/containers/common/HeaderContainer.tsx
  src/containers/home/RecruitPostsContainer.test.tsx
  src/containers/home/RecruitPostsContainer.tsx
Labels: Bugfix/Function

#209 [Imporve] Main Page에서 호출 중인 API를 React Query를 적용하라
  jest.setup.js
  package.json
  src/components/home/TagsBar.test.tsx
  src/components/home/TagsBar.tsx
  src/containers/home/RecruitPostsContainer.test.tsx
  src/containers/home/RecruitPostsContainer.tsx
  src/containers/home/StatusBarContainer.test.tsx
  src/containers/home/StatusBarContainer.tsx
  src/hooks/api/useFetchGroups.test.ts
  src/hooks/api/useFetchGroups.ts
  src/hooks/api/useFetchTagsCount.test.ts
  src/hooks/api/useFetchTagsCount.ts
  src/pages/_app.page.tsx
  src/pages/index.test.tsx
  src/recoil/group/atom.ts
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/services/api/__mocks__/group.ts
  src/services/api/group.test.ts
  src/services/api/group.ts
  src/services/api/tagsCount.test.ts
  src/services/api/tagsCount.ts
  src/test/InjectMockProviders.tsx
  src/test/InjectTestingRecoilState.tsx
  src/test/ReactQueryWrapper.tsx
  yarn.lock
Labels: Improve/Function

#211 [Improve] 내 정보 페이지의 신청한 팀 목록, 모집한 팀 목록을 React Query를 적용하라
  fixtures/initialStore.ts
  src/containers/home/RecruitPostsContainer.test.tsx
  src/containers/home/RecruitPostsContainer.tsx
  src/containers/home/StatusBarContainer.test.tsx
  src/containers/home/StatusBarContainer.tsx
  src/containers/myInfo/AppliedGroupsContainer.test.tsx
  src/containers/myInfo/AppliedGroupsContainer.tsx
  src/containers/myInfo/RecruitedGroupsContainer.test.tsx
  src/containers/myInfo/RecruitedGroupsContainer.tsx
  src/hooks/api/useFetchGroups.ts
  src/hooks/api/useFetchTagsCount.test.ts
  src/hooks/api/useFetchTagsCount.ts
  src/hooks/api/useFetchUserAppliedGroups.test.ts
  src/hooks/api/useFetchUserAppliedGroups.ts
  src/hooks/api/useFetchUserRecruitedGroups.test.ts
  src/hooks/api/useFetchUserRecruitedGroups.ts
  src/hooks/useCatchErrorWithToast.test.ts
  src/hooks/useCatchErrorWithToast.ts
  src/pages/myinfo/applied.test.tsx
  src/pages/myinfo/recruited.test.tsx
  src/pages/signup.test.tsx
  src/reducers/myInfoSlice.test.ts
  src/reducers/myInfoSlice.ts
  src/reducers/rootReducer.test.ts
  src/reducers/rootReducer.ts
  src/services/api/applicants.ts
  src/services/api/group.test.ts
  src/services/api/group.ts
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: Refactor, Improve/Function
