Repository mbti-nf-team/soople, pull requests merged in 2022-02, with the labels that each got.

#215 [Refactor] Hooks api의 파일 위치를 변경하라
  src/containers/detail/CommentsContainer.test.tsx
  src/containers/detail/CommentsContainer.tsx
  src/containers/detail/DetailContentsContainer.test.tsx
  src/containers/detail/DetailContentsContainer.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/containers/home/RecruitPostsContainer.test.tsx
  src/containers/home/RecruitPostsContainer.tsx
  src/containers/home/StatusBarContainer.test.tsx
  src/containers/home/StatusBarContainer.tsx
  src/containers/myInfo/AppliedGroupsContainer.test.tsx
  src/containers/myInfo/AppliedGroupsContainer.tsx
  src/containers/myInfo/RecruitedGroupsContainer.test.tsx
  src/containers/myInfo/RecruitedGroupsContainer.tsx
  src/hooks/api/applicant/useApplyGroup.test.ts
  src/hooks/api/applicant/useApplyGroup.ts
  src/hooks/api/applicant/useCancelApply.test.ts
  src/hooks/api/applicant/useCancelApply.ts
  src/hooks/api/applicant/useFetchApplicants.test.ts
  src/hooks/api/applicant/useFetchApplicants.ts
  src/hooks/api/comment/useAddComment.test.ts
  src/hooks/api/comment/useAddComment.ts
  src/hooks/api/comment/useDeleteComment.test.ts
  src/hooks/api/comment/useDeleteComment.ts
  src/hooks/api/comment/useFetchComments.test.ts
  src/hooks/api/comment/useFetchComments.ts
  src/hooks/api/group/useFetchGroup.test.ts
  src/hooks/api/group/useFetchGroup.ts
  src/hooks/api/group/useFetchGroups.test.ts
  src/hooks/api/group/useFetchGroups.ts
  src/hooks/api/group/useFetchUserAppliedGroups.test.ts
  src/hooks/api/group/useFetchUserAppliedGroups.ts
  src/hooks/api/group/useFetchUserRecruitedGroups.test.ts
  src/hooks/api/group/useFetchUserRecruitedGroups.ts
  src/hooks/api/tagsCount/useFetchTagsCount.test.ts
  src/hooks/api/tagsCount/useFetchTagsCount.ts
  src/hooks/api/useCatchErrorWithToast.test.ts
  src/hooks/api/useCatchErrorWithToast.ts
  src/pages/detail/[id].test.tsx
  src/pages/index.test.tsx
  src/pages/myinfo/applied.test.tsx
  src/pages/myinfo/recruited.test.tsx
Labels: Refactor

#216 [Improve] SignInModal과 PublishModal의 Client State를 Recoil로 변경하라
  src/containers/auth/SignInModalContainer.test.tsx
  src/containers/auth/SignInModalContainer.tsx
  src/containers/common/HeaderContainer.test.tsx
  src/containers/common/HeaderContainer.tsx
  src/containers/detail/CommentsContainer.test.tsx
  src/containers/detail/CommentsContainer.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/containers/write/PublishModalContainer.test.tsx
  src/containers/write/PublishModalContainer.tsx
  src/containers/write/WriteHeaderContainer.test.tsx
  src/containers/write/WriteHeaderContainer.tsx
  src/pages/write.test.tsx
  src/recoil/modal/atom.ts
  src/reducers/authSlice.test.ts
  src/reducers/authSlice.ts
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/test/InjectTestingRecoilState.tsx
Labels: Refactor, Improve/Function

#218 [Improve] 신청 현황 보기 페이지를 React Query를 적용하라
  src/containers/applicants/ApplicationStatusContainer.test.tsx
  src/containers/applicants/ApplicationStatusContainer.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.tsx
  src/hooks/api/applicant/useUpdateApplicant.test.ts
  src/hooks/api/applicant/useUpdateApplicant.ts
  src/hooks/api/group/useUpdateCompletedApply.test.ts
  src/hooks/api/group/useUpdateCompletedApply.ts
  src/pages/detail/[id]/applicants.page.tsx
  src/pages/detail/[id]/applicants.test.tsx
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
Labels: Refactor, Improve/Function

#220 [Improve] 글 작성시에 필요한 Recoil 적용 및 API를 React Query로 변경하라
  fixtures/initialStore.ts
  src/components/write/PublishModalForm.test.tsx
  src/components/write/PublishModalForm.tsx
  src/components/write/WriteForm.test.tsx
  src/components/write/WriteForm.tsx
  src/containers/write/PublishModalContainer.test.tsx
  src/containers/write/PublishModalContainer.tsx
  src/containers/write/WriteFormContainer.test.tsx
  src/containers/write/WriteFormContainer.tsx
  src/containers/write/WriteHeaderContainer.test.tsx
  src/containers/write/WriteHeaderContainer.tsx
  src/hooks/api/group/usePublishNewGroup.test.ts
  src/hooks/api/group/usePublishNewGroup.ts
  src/models/group.ts
  src/models/index.ts
  src/pages/write.test.tsx
  src/recoil/group/atom.ts
  src/reducers/groupSlice.test.ts
  src/reducers/groupSlice.ts
  src/reducers/rootReducer.test.ts
  src/reducers/rootReducer.ts
  src/test/InjectTestingRecoilState.tsx
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: Refactor, Improve/Function

#223 [UI/UX] 유저 드롭다운 디자인 CSS를 개선하라
  src/components/common/DropDown.tsx
Labels: UI/UX

#225 [Improve] SignOut, SignUp, fetch user profile API를 React Query로 구현하라
  src/hooks/api/auth/useFetchUserProfile.test.ts
  src/hooks/api/auth/useFetchUserProfile.ts
  src/hooks/api/auth/useSignOut.test.ts
  src/hooks/api/auth/useSignOut.ts
  src/hooks/api/auth/useSignUp.test.ts
  src/hooks/api/auth/useSignUp.ts
Labels: Refactor, Improve/Function

#226 [UI/UX] 모집한 팀, 신청한 팀 리스트 컴포넌트에 CSS를 적용하라
  src/components/myInfo/MyGroup.tsx
  src/components/myInfo/MyGroups.tsx
Labels: UI/UX

#227 [Fix] CodeCov Coverage broken error
  .github/workflows/ci.yml
Labels: Bugfix/Function

#233 [Feature] CreatebleSelect 공통 컴포넌트 구현하라
  package.json
  src/components/auth/SignUpForm.test.tsx
  src/components/auth/SignUpForm.tsx
  src/components/common/CreatableSelectBox.test.tsx
  src/components/common/CreatableSelectBox.tsx
  src/components/common/HelperMessage.test.tsx
  src/components/common/HelperMessage.tsx
  src/components/common/Input.tsx
  src/components/common/Label.test.tsx
  src/components/common/Label.tsx
  src/containers/auth/SignUpContainer.test.tsx
  src/models/group.ts
  src/models/index.ts
  yarn.lock
Labels: Feature/Function, UI/UX

#235 [Feature] 글 모집 상태에 따른 모집 상태 정보 구현하라
  src/components/detail/DetailHeaderSection.tsx
  src/components/home/RecruitPost.tsx
  src/components/myInfo/MyGroup.tsx
  src/components/myInfo/MyGroups.tsx
  src/components/myInfo/MyInfoLayout.tsx
  src/components/myInfo/MyInfoTab.test.tsx
  src/components/myInfo/MyInfoTab.tsx
  src/containers/myInfo/MyInfoTabContainer.test.tsx
  src/containers/myInfo/MyInfoTabContainer.tsx
  src/hooks/useGroupRecruitmentStatus.test.ts
  src/hooks/useGroupRecruitmentStatus.ts
  src/hooks/useMyInfoRecruitmentStatus.ts
  src/hooks/useRecruitDateStatus.test.ts
  src/hooks/useRecruitDateStatus.ts
  src/models/group.ts
  src/pages/myinfo/setting.page.tsx
Labels: Feature/Function

#241 [Feature] Select Box 공통 컴포넌트를 구현하라
  src/components/common/SelectBox.test.tsx
  src/components/common/SelectBox.tsx
  src/components/home/FilterBar.test.tsx
  src/components/home/FilterBar.tsx
  src/containers/home/StatusBarContainer.test.tsx
  src/containers/home/StatusBarContainer.tsx
Labels: Feature/Function

#239 [Feature] MyGroup에 모집 상태를 적용하라
  src/components/myInfo/MyGroup.test.tsx
  src/components/myInfo/MyGroup.tsx
Labels: Feature/Function, UI/UX

#237 [Feature] MyInfoTab에 모집한 팀, 신청한 팀의 개수를 추가하라
  src/components/myInfo/MyInfoTab.test.tsx
  src/components/myInfo/MyInfoTab.tsx
  src/containers/myInfo/MyInfoTabContainer.test.tsx
  src/containers/myInfo/MyInfoTabContainer.tsx
Labels: Feature/Function

#243 [UXUI] Sign Up 페이지에 디자인 폼을 적용하라
  src/components/auth/SignUpForm.test.tsx
  src/components/auth/SignUpForm.tsx
  src/components/common/Header.test.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/containers/auth/SignUpContainer.tsx
  src/containers/common/HeaderContainer.tsx
  src/pages/signup.page.tsx
  src/pages/signup.test.tsx
Labels: UI/UX

#249 [Feature] 알람 페이지에서 사용자의 승인, 거절 알람 리스트를 볼 수 있게하라
  fixtures/alarm.ts
  src/components/alarm/AlarmItem.test.tsx
  src/components/alarm/AlarmItem.tsx
  src/components/alarm/Alarms.test.tsx
  src/components/alarm/Alarms.tsx
  src/components/common/UserNavbar.tsx
  src/containers/alarm/AlarmListContainer.test.tsx
  src/containers/alarm/AlarmListContainer.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.tsx
  src/hooks/api/alarm/useFetchAlarms.test.ts
  src/hooks/api/alarm/useFetchAlarms.ts
  src/hooks/api/group/useUpdateCompletedApply.test.ts
  src/hooks/api/group/useUpdateCompletedApply.ts
  src/models/alarm.ts
  src/pages/alarm.page.tsx
  src/pages/alarm.test.tsx
  src/services/api/alarm.test.ts
  src/services/api/alarm.ts
  src/services/api/group.ts
  src/utils/firestore.test.ts
  src/utils/firestore.ts
Labels: Feature/Function

#251 [Feature] 사용자가 신청시 작성자에게 알람에 추가되도록 하라
  src/components/home/RecruitPosts.tsx
  src/containers/detail/DetailHeaderContainer.test.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/containers/home/RecruitPostsContainer.tsx
  src/hooks/api/applicant/useApplyGroup.test.ts
  src/hooks/api/applicant/useApplyGroup.ts
  src/models/group.ts
Labels: Feature/Function

#253 [Feature] Custom 404, 500 페이지를 구현하라
  src/components/common/Header.test.tsx
  src/components/common/Header.tsx
  src/components/common/HeaderWrapper.test.tsx
  src/components/common/HeaderWrapper.tsx
  src/containers/common/HeaderContainer.tsx
  src/pages/404.page.tsx
  src/pages/404.test.tsx
  src/pages/500.page.tsx
  src/pages/500.test.tsx
  src/styles/GlobalStyles.test.tsx
  src/styles/GlobalStyles.tsx
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: Feature/Function

#255 [UI-UX] Toast Message success 및 error 컴포넌트 CSS를 적용하라
  src/assets/icons/check.svg
  src/components/common/Core.tsx
  src/containers/home/RecruitPostsContainer.test.tsx
  src/containers/home/RecruitPostsContainer.tsx
  src/hooks/api/useCatchErrorWithToast.test.ts
  src/hooks/api/useCatchErrorWithToast.ts
  src/styles/GlobalStyles.tsx
  src/styles/StyledToastContainer.ts
  src/utils/__mocks__/toast.tsx
  src/utils/toast.test.tsx
  src/utils/toast.tsx
Labels: UI/UX

#263 [Fix] 디자인 피드백을 반영하라
  src/components/common/Button.tsx
  src/components/detail/ApplicantStatusButton.test.tsx
  src/components/detail/ApplicantStatusButton.tsx
  src/components/detail/CommentForm.test.tsx
  src/components/detail/CommentForm.tsx
  src/components/detail/CommentView.test.tsx
  src/components/detail/CommentView.tsx
  src/components/detail/CommentsView.test.tsx
  src/components/detail/CommentsView.tsx
  src/containers/detail/CommentsContainer.test.tsx
  src/containers/detail/CommentsContainer.tsx
  src/hooks/__mocks__/useRenderSuccessToast.ts
  src/hooks/api/comment/useDeleteComment.test.ts
  src/hooks/api/comment/useDeleteComment.ts
  src/hooks/useRenderSuccessToast.test.ts
  src/hooks/useRenderSuccessToast.ts
Labels: Bugfix/UI, Bugfix/Function

#266 [Install] Remirror Dependencies
  package.json
  src/pages/editor.page.tsx
  yarn.lock
Labels: 🛠 Setting

#268 [Feature] 글 작성시에 에디터를 적용하라
  package.json
  src/components/detail/DetailContentsSection.tsx
  src/components/home/RecruitPost.tsx
  src/components/myInfo/MyGroup.tsx
  src/components/write/EditorToolbar.test.tsx
  src/components/write/EditorToolbar.tsx
  src/components/write/RemirorEditorProvider.tsx
  src/components/write/WriteEditor.tsx
  src/components/write/WriteForm.test.tsx
  src/components/write/WriteForm.tsx
  src/containers/write/PublishModalContainer.test.tsx
  src/containers/write/PublishModalContainer.tsx
  src/containers/write/WriteFormContainer.test.tsx
  src/pages/editor.page.tsx
  src/pages/write.page.tsx
  src/pages/write.test.tsx
  src/utils/utils.test.ts
  src/utils/utils.ts
  yarn.lock
Labels: Feature/Function

#271 [Improve] 모집 마감 안보기 상태를 localStorage에 저장하여 유지시켜라
  src/components/common/SwitchButton.tsx
  src/components/home/RecruitPost.test.tsx
  src/components/home/RecruitPost.tsx
  src/containers/home/StatusBarContainer.test.tsx
  src/containers/home/StatusBarContainer.tsx
  src/pages/index.test.tsx
  src/recoil/group/atom.ts
  src/services/storage.test.ts
  src/services/storage.ts
Labels: Improve/Function

#278 [Improve] Sign Up을 한 사용자만 세션이 유지되도록 변경하라
  src/components/auth/SignUpForm.tsx
  src/components/common/Core.test.tsx
  src/components/common/Core.tsx
  src/components/common/Header.test.tsx
  src/components/common/Header.tsx
  src/components/common/UserNavbar.test.tsx
  src/components/common/UserNavbar.tsx
  src/components/detail/CommentView.tsx
  src/components/detail/CommentsView.tsx
  src/containers/auth/SignInModalContainer.test.tsx
  src/containers/auth/SignInModalContainer.tsx
  src/containers/auth/SignUpContainer.tsx
  src/containers/common/HeaderContainer.test.tsx
  src/containers/common/HeaderContainer.tsx
  src/containers/detail/CommentsContainer.test.tsx
  src/containers/detail/CommentsContainer.tsx
  src/containers/myInfo/AppliedGroupsContainer.test.tsx
  src/containers/myInfo/AppliedGroupsContainer.tsx
  src/containers/myInfo/MyInfoTabContainer.tsx
  src/containers/myInfo/RecruitedGroupsContainer.test.tsx
  src/containers/myInfo/RecruitedGroupsContainer.tsx
  src/containers/write/WriteFormContainer.test.tsx
  src/containers/write/WriteFormContainer.tsx
  src/hooks/api/alarm/useFetchAlarms.test.ts
  src/hooks/api/alarm/useFetchAlarms.ts
  src/hooks/api/auth/useFetchUserProfile.test.ts
  src/hooks/api/auth/useFetchUserProfile.ts
  src/hooks/api/auth/useGetUserToken.test.ts
  src/hooks/api/auth/useGetUserToken.ts
  src/hooks/api/auth/useRefreshToken.test.ts
  src/hooks/api/auth/useRefreshToken.ts
  src/hooks/api/auth/useSignOut.ts
  src/pages/alarm.test.tsx
  src/pages/myinfo/applied.test.tsx
  src/pages/myinfo/recruited.test.tsx
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: Bugfix/Function, Improve/Function

#283 [Fix] 읽지 않은 알람이 존재하지 않은 경우 알람 상태가 안보이게 수정하라
  src/components/common/UserNavbar.tsx
Labels: Bugfix/Function

#285 [Feature] 내 정보 페이지 UI 컴포넌트 구현 및 CSS 적용하라
  public/img_avatar_default.png
  src/assets/icons/img_avatar_default.svg
  src/components/auth/SignUpForm.tsx
  src/components/common/Button.test.tsx
  src/components/common/Button.tsx
  src/components/common/CreatableSelectBox.tsx
  src/components/common/ProfileImage.test.tsx
  src/components/common/ProfileImage.tsx
  src/components/myInfo/ImageSetting.test.tsx
  src/components/myInfo/ImageSetting.tsx
  src/components/myInfo/MyInfoTab.tsx
  src/components/myInfo/SettingForm.test.tsx
  src/components/myInfo/SettingForm.tsx
  src/containers/myInfo/MyInfoSettingContainer.test.tsx
  src/containers/myInfo/MyInfoSettingContainer.tsx
  src/hooks/api/auth/useSignOut.test.ts
  src/hooks/api/auth/useSignOut.ts
  src/models/group.ts
  src/pages/_app.page.tsx
  src/pages/myinfo/setting.page.tsx
  src/pages/myinfo/setting.test.tsx
  src/styles/zIndexes.ts
Labels: Feature/Function, UI/UX

#272 [UI/UX] 알람 목록에 CSS를 적용하라
  src/assets/icons/img_alarm_confirmed.svg
  src/assets/icons/img_alarm_rejected.svg
  src/components/alarm/AlarmItem.test.tsx
  src/components/alarm/AlarmItem.tsx
  src/components/alarm/Alarms.test.tsx
  src/components/alarm/Alarms.tsx
  src/components/applicants/ApplicationStatus.tsx
  src/components/common/EmptyStateArea.tsx
  src/components/myInfo/MyGroups.tsx
  src/containers/alarm/AlarmListContainer.test.tsx
  src/containers/alarm/AlarmListContainer.tsx
  src/services/api/alarm.ts
Labels: Feature/Function, UI/UX

#274 [Fix] 스터디 및 프로젝트 신청 시 알람이 잘못 노출되는 오류를 수정하라
  fixtures/alarm.ts
  src/components/alarm/AlarmItem.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
  src/containers/applicants/ApplicationStatusHeaderContainer.tsx
  src/containers/detail/DetailHeaderContainer.tsx
  src/hooks/api/applicant/useApplyGroup.ts
  src/models/alarm.ts
  src/utils/firestore.test.ts
  src/utils/firestore.ts
Labels: Bugfix/Function
